### ISSUE TITLE
Controller panics when alb.ingress.kubernetes.io/scheme is modified

### ISSUE THREAD

**Issue by joshrosso** [kubernetes-sigs/aws-alb-ingress-controller#322]
Panic occurs under the following condition.

The following resource is satisfied by the ingress controller.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver
  namespace: echoserver
  annotations:
    #alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/security-groups: b
    alb.ingress.kubernetes.io/subnets: a
    alb.ingress.kubernetes.io/successCodes: "200"
    kubernetes.io/ingress.class: alb
spec:
  rules:
  - host: echoserver.somedomain.io
    http:
      paths:
      - path: /
        backend:
          serviceName: echoserver
          servicePort: 80
```

Then the user changes the `alb.ingress.kubernetes.io` to `internet-facing`, as seen below.

```
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    #alb.ingress.kubernetes.io/scheme: internal
```

The following panic occurs.

```
I0205 19:29:18.016652       7 listener.go:93] [ALB-INGRESS] [echoserver/echoserver] [INFO]: Start Listener creation.
E0205 19:29:18.044239       7 listener.go:145] [ALB-INGRESS] [echoserver/echoserver] [ERROR]: Failed Listener creation: TargetGroupAssociationLimit: Target group 'arn:aws:elasticloadbalancing:us-east-1:dfgdsf392:targetgroup/sandbox1-32095-HTTP-fsdfgds40/7sdfgfds219f1da5' cannot be associated with more than one load balancer
E0205 19:29:18.044266       7 listener.go:145] [ALB-INGRESS] [echoserver/echoserver] [ERROR]:   status code: 400, request id: db9827c5-0aaa-11e8-ae20-abc1d808f34d.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1564f88]

goroutine 13139 [running]:
github.com/coreos/alb-ingress-controller/pkg/alb/rules.Rules.FindUnusedTGs(0xc423053f80, 0x2, 0x2, 0xc4208e24e8, 0x1, 0x1, 0x0, 0x1, 0xc4263e1a70)
        /go/src/github.com/coreos/alb-ingress-controller/pkg/alb/rules/rules.go:110 +0x78
github.com/coreos/alb-ingress-controller/pkg/alb/loadbalancer.(*LoadBalancer).Reconcile(0xc4229b41e0, 0xc426b0ff58, 0xc4231f4760, 0x7f4dec585000, 0x0)
        /go/src/github.com/coreos/alb-ingress-controller/pkg/alb/loadbalancer/loadbalancer.go:252 +0x95e
github.com/coreos/alb-ingress-controller/pkg/albingress.(*ALBIngress).Reconcile(0xc426acc0b0, 0xc4205927b8)
        /go/src/github.com/coreos/alb-ingress-controller/pkg/albingress/albingress.go:321 +0xb4
github.com/coreos/alb-ingress-controller/pkg/controller.(*ALBController).update.func1(0xc422436aa0, 0xc426acc0b0)
        /go/src/github.com/coreos/alb-ingress-controller/pkg/controller/alb-controller.go:180 +0xa4
created by github.com/coreos/alb-ingress-controller/pkg/controller.(*ALBController).update
        /go/src/github.com/coreos/alb-ingress-controller/pkg/controller/alb-controller.go:178 +0x49e

```

**Comment by bigkraig** [comment]
No longer an issue
