### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by natefox** [kubernetes-sigs/aws-alb-ingress-controller#345]
Running `quay.io/coreos/alb-ingress-controller:1.0-alpha.8` and got this:
```
{"log":"I0314 07:39:32.721612       1 rule.go:105] [ALB-INGRESS] [php-apache-ns/php-apache-ing] [INFO]: Start Rule deletion.\n","stream":"stderr","time":"2018-03-14T07:39:32.721853803Z"}
{"log":"I0314 07:39:33.175373       1 rule.go:110] [ALB-INGRESS] [php-apache-ns/php-apache-ing] [INFO]: Completed Rule deletion. Rule Priority: \"1\" | Condition: [{    Field: \"path-pattern\",    Values: [\"/\"]  }]\n","stream":"stderr","time":"2018-03-14T07:39:33.175649941Z"}
{"log":"panic: runtime error: slice bounds out of range\n","stream":"stderr","time":"2018-03-14T07:40:25.184095654Z"}
{"log":"\n","stream":"stderr","time":"2018-03-14T07:40:25.184118503Z"}
{"log":"goroutine 130 [running]:\n","stream":"stderr","time":"2018-03-14T07:40:25.184121666Z"}
{"log":"github.com/coreos/alb-ingress-controller/pkg/controller.(*ALBController).update(0xc42022f950)\n","stream":"stderr","time":"2018-03-14T07:40:25.184124443Z"}
{"log":"\u0009/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/pkg/controller/alb-controller.go:188 +0x82d\n","stream":"stderr","time":"2018-03-14T07:40:25.184127405Z"}
{"log":"github.com/coreos/alb-ingress-controller/pkg/controller.(*ALBController).startPolling(0xc42022f950)\n","stream":"stderr","time":"2018-03-14T07:40:25.184130746Z"}
{"log":"\u0009/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/pkg/controller/alb-controller.go:111 +0x12d\n","stream":"stderr","time":"2018-03-14T07:40:25.184133801Z"}
{"log":"created by github.com/coreos/alb-ingress-controller/pkg/controller.(*ALBController).Configure\n","stream":"stderr","time":"2018-03-14T07:40:25.184136516Z"}
{"log":"\u0009/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/pkg/controller/alb-controller.go:103 +0x209\n","stream":"stderr","time":"2018-03-14T07:40:25.184139381Z"}
```

Apologies for the raw logs, my `kubectl logs` is borked right now for non-alb related reasons :)

**Comment by bigkraig** [comment]
Can you test with `1.0-beta.2` and re-open if this is still happening? This should be fixed. Thanks!
