### ISSUE TITLE
Panic during ALB deletion

### ISSUE THREAD

**Issue by rifelpet** [kubernetes-sigs/aws-alb-ingress-controller#454]
I'm running 1.0-beta3 and received the following panic when I deleted an ingress resource:

```I0712 22:49:32.025290       1 loadbalancer.go:302] [ALB-INGRESS] [ops/ops-internal-test] [INFO]: Start ELBV2 deletion.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15cef18]

goroutine 215 [running]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/alb/tg.(*TargetGroup).needsModification(0xc000669450, 0x10)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/alb/tg/targetgroup.go:331 +0x58
github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/alb/tg.(*TargetGroup).Reconcile(0xc000669450, 0xc000cade80, 0xc00044cdf0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/alb/tg/targetgroup.go:167 +0x56
github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/alb/tg.TargetGroups.Reconcile(0xc0002aa070, 0x2, 0x2, 0xc000cade80, 0x1, 0xc00044cdf0, 0x0, 0x1, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/alb/tg/targetgroups.go:55 +0x85
github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/alb/lb.(*LoadBalancer).Reconcile(0xc00083f080, 0xc000cadf60, 0xc0006993d8, 0x7f09393146c0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/alb/lb/loadbalancer.go:338 +0x141
github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/albingress.(*ALBIngress).Reconcile(0xc000784420, 0xc0008997b8)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/albingress/albingress.go:253 +0xb5
github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/albingress.ALBIngresses.Reconcile.func1(0xc0000768e0, 0xc000784420)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/albingress/albingresses.go:164 +0x99
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/albingress.ALBIngresses.Reconcile
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/albingress/albingresses.go:162 +0x87
```

There are other ingress resources with identical backends (`serviceName` and `servicePort`), so it may have something to do with shared target groups across ALBs.

I can provide additional info if necessary.

**Comment by bigkraig** [comment]
@rifelpet I came across this earlier and have it fixed in master, but I haven't cut a new release yet. The image id is `9fa0225`

**Comment by rifelpet** [comment]
@bigkraig looks like that fixed the issue. thanks!
