### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tatobi** [kubernetes-sigs/aws-alb-ingress-controller#488]
```
I0726 05:46:22.152972       1 main.go:24] [ALB-INGRESS] [controller] [INFO]: Log level read as "", defaulting to INFO. To change, set LOG_LEVEL environment variable to WARN, ERROR, or DEBUG.
I0726 05:46:22.153260       1 launch.go:112] &{ALB Ingress Controller 1.0-beta.4 git-385f5365 git://github.com/kubernetes-sigs/aws-alb-ingress-controller}
I0726 05:46:22.153474       1 launch.go:282] Creating API client for https://100.64.0.1:443
I0726 05:46:22.164144       1 launch.go:294] Running in Kubernetes Cluster version v1.9 (v1.9.8) - git (clean) commit c138b85178156011dc934c2c9f4837476876fb07 - platform linux/amd64
I0726 05:46:22.165387       1 launch.go:134] validated kube-system/default-http-backend as the default backend
I0726 05:46:22.168938       1 alb-controller.go:130] [ALB-INGRESS] [controller] [INFO]: albNamePrefix undefined, defaulting to 857ba8bb
I0726 05:46:22.405589       1 albingresses.go:83] [ALB-INGRESS] [ingress] [INFO]: Building list of existing ALBs
I0726 05:46:22.517567       1 albingresses.go:91] [ALB-INGRESS] [ingress] [INFO]: Fetching information on 0 ALBs
I0726 05:46:22.532672       1 albingresses.go:108] [ALB-INGRESS] [ingress] [INFO]: Assembled 0 ingresses from existing AWS resources in 127.046242ms
I0726 05:46:22.532706       1 controller.go:1359] starting Ingress controller
I0726 05:46:22.534792       1 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"dask-scheduler-ingress", UID:"dad2c21d-9053-11e8-83be-06f8616dbe34", APIVersion:"extensions", ResourceVersion:"2115", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress default/dask-scheduler-ingress
I0726 05:46:22.534826       1 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"dask-https-ingress", UID:"d16a9e07-9053-11e8-83be-06f8616dbe34", APIVersion:"extensions", ResourceVersion:"2060", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress default/dask-https-ingress
I0726 05:46:22.738487       1 controller.go:477] backend reload required
I0726 05:46:22.738914       1 leaderelection.go:174] attempting to acquire leader lease...
I0726 05:46:22.743857       1 leaderelection.go:184] successfully acquired lease kube-system/ingress-controller-leader-alb
I0726 05:46:22.743895       1 status.go:193] new leader elected: alb-ingress-controller-7bf9957c78-4kr55
E0726 05:46:22.813957       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:522
/home/travis/.gimme/versions/go/src/runtime/panic.go:513
/home/travis/.gimme/versions/go/src/runtime/panic.go:82
/home/travis/.gimme/versions/go/src/runtime/signal_unix.go:390
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/aws/albec2/ec2.go:725
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/annotations/annotations.go:495
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/annotations/annotations.go:154
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/albingress/albingress.go:99
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/albingress/albingresses.go:53
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/controller/alb-controller.go:217
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/controller/alb-controller.go:200
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:479
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:175
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:89
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:1333
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x144dd73]

goroutine 149 [running]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x1829aa0, 0x2e2c810)
        /home/travis/.gimme/versions/go/src/runtime/panic.go:513 +0x1b9
github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/aws/albec2.ClusterSubnets(0x0, 0xc00004200d, 0x25, 0xc0003c8b40, 0x2e650a0, 0x43c8c3, 0x16f4700, 0x380, 0xc0002c25a0)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/aws/albec2/ec2.go:725 +0x73
github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/annotations.(*Annotations).setSubnets(0xc00040a3c0, 0xc000328240, 0xc00004200d, 0x25, 0xc0003c8b40, 0x1c8de80, 0x2e63fd8, 0x2e63fd8, 0x1c6d080)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/annotations/annotations.go:495 +0x1387
github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/annotations.(*ValidatingAnnotationFactory).ParseAnnotations(0xc000276480, 0xc000323a80, 0x0, 0x34, 0x4719d2)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/annotations/annotations.go:154 +0x774
github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/albingress.NewALBIngressFromIngress(0xc000203c00, 0x0)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/albingress/albingress.go:99 +0x1ec
github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/albingress.NewALBIngressesFromIngresses(0xc000877908, 0xc0006df930, 0x2, 0x2)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/albingress/albingresses.go:53 +0x2d1
github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/controller.(*albController).update(0xc00040a140)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/controller/alb-controller.go:217 +0x386
github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/controller.(*albController).OnUpdate(0xc00040a140, 0xc000398680, 0x3, 0x3, 0xc0003986a0, 0x3, 0x3, 0x2e63fd8, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/pkg/controller/alb-controller.go:200 +0x2b
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).syncIngress(0xc00040a500, 0x171d760, 0xc00070a140, 0xc00070a140, 0xc0007add00)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:479 +0x7b8
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).syncIngress-fm(0x171d760, 0xc00070a140, 0xa, 0xc0007ade20)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:175 +0x3e
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).worker(0xc0002f8030)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:89 +0x115
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).worker-fm()
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x2a
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0007adfa8)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000877fa8, 0x3b9aca00, 0x0, 0x7fbf24f48101, 0xc0000864e0)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0007adfa8, 0x3b9aca00, 0xc0000864e0)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).Run(0xc0002f8030, 0x3b9aca00, 0xc0000864e0)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x5d
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.GenericController.Start
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:1390 +0x4a8
```
Ingresses:
-------------------
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dask-https-ingress
  namespace: default
  labels:
    run: dask-https-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:***********************************"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/successCodes: 301,302,200
    alb.ingress.kubernetes.io/security-groups: sg-71c7ad3b
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: 15
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: 35
spec:
  rules:
  - host: jupyter-tobi-test-node-load-n6ls7xox. *******************.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ***************-dask-jupyter
          servicePort: 80

```
-----------------------
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dask-scheduler-ingress
  namespace: default
  labels:
    run: dask-scheduler-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:***************************************"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/successCodes: 301,302,200
    alb.ingress.kubernetes.io/security-groups: sg-71c7ad3b
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: 15
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: 35
spec:
  rules:
  - host: scheduler-tobi-test-node-load-n6ls7xox.*******************.com
    http:
      paths:
      - path: /
        backend:
          serviceName: *******************-dask-scheduler-nodeport
          servicePort: 80
```

**Comment by tatobi** [comment]
The problem solved by using quotation around seconds, BUT it shouldn't crash and go loop into CrashLoop by using integers in place of seconds, which are basically not strings, numbers, integers (logically)... 
the working configuration:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dask-scheduler-ingress
  namespace: default
  labels:
    run: dask-scheduler-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:***************************************"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/successCodes: 301,302,200
    alb.ingress.kubernetes.io/security-groups: sg-71c7ad3b
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "35"
spec:
  rules:
  - host: scheduler-tobi-test-node-load-n6ls7xox.*******************.com
    http:
      paths:
      - path: /
        backend:
          serviceName: *******************-dask-scheduler-nodeport
          servicePort: 80
```

**Comment by bigkraig** [comment]
The annotations parsing has been replaced and now leverages some of the k8s native int or string types for this, so it should be handled more gracefully now.

I'm not able to test it out though, using kubectl edit I get errors when setting integers in my annotations?

```
error: ingresses.extensions "ingressName" could not be patched: cannot convert int64 to string
```
