### ISSUE TITLE
Controller goes into CrashBackOffLoop when redirect rule is manually added to ALB

### ISSUE THREAD

**Issue by akshayks** [kubernetes-sigs/aws-alb-ingress-controller#532]
I seem to have inadvertently caused the ALB Ingress Controller to crash by manually adding an `HTTP -> HTTPS` redirect rule to an ALB it managed. Here is the output of `kubectl logs` on the controller pod:
```
I0807 01:58:03.682792       1 flags.go:131] Watching for Ingress class: alb
W0807 01:58:03.682932       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0807 01:58:03.683125       1 main.go:159] Creating API client for https://172.20.0.1:443
-------------------------------------------------------------------------------
AWS ALB Ingress controller
  Release:    1.0-beta.5
  Build:      git-8351be1a
  Repository: https://github.com/kubernetes-sigs/aws-alb-ingress-controller
-------------------------------------------------------------------------------

I0807 01:58:03.698474       1 main.go:203] Running in Kubernetes cluster version v1.10 (v1.10.3) - git (clean) commit 2bba0127d85d5a46ab4b778548be28623b32d0b0 - platform linux/amd64
I0807 01:58:03.699173       1 alb.go:85] ALB resource names will be prefixed with 01247690
I0807 01:58:03.705627       1 alb.go:158] Starting AWS ALB Ingress controller
I0807 01:58:04.245767       1 albingresses.go:64] Building list of existing ALBs
I0807 01:58:04.386069       1 albingresses.go:72] Fetching information on 2 ALBs
I0807 01:58:04.910617       1 targetgroups.go:97] app-lab0/dev-us-west-2-z0-lab0: Fetching Targets for Target Group arn:aws:elasticloadbalancing:us-west-2:164634912905:targetgroup/01247690-nginx-dev-6dc431f8d/3b57fbd572b04a7c
I0807 01:58:04.932984       1 targetgroups.go:97] kube-system/dev-us-west-2-kube-system: Fetching Targets for Target Group arn:aws:elasticloadbalancing:us-west-2:164634912905:targetgroup/01247690-cargo-dashboard-kub/ed7367762658bd31
I0807 01:58:04.969364       1 rules.go:26] app-lab0/dev-us-west-2-z0-lab0: Fetching Rules for Listener arn:aws:elasticloadbalancing:us-west-2:164634912905:listener/app/01247690-applab0-devuswest-502b/24d94ecae4c7450f/b8fab670d065b7a7
I0807 01:58:04.982761       1 rules.go:26] app-lab0/dev-us-west-2-z0-lab0: Fetching Rules for Listener arn:aws:elasticloadbalancing:us-west-2:164634912905:listener/app/01247690-applab0-devuswest-502b/24d94ecae4c7450f/cbaebb21ae5c998e
F0807 01:58:04.996191       1 albingresses.go:208] ERROR: Work Unit failed due to a recoverable error: 'runtime error: invalid memory address or nil pointer dereference'
, Stack Trace:
 goroutine 80 [running]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1.1(0xc0008d1f18, 0xc0006ce2c0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:60 +0xbc
panic(0x1683760, 0x2c1cd90)
	/home/travis/.gimme/versions/go/src/runtime/panic.go:513 +0x1b9
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/rs.NewCurrentRules(0xc0008d19d8, 0xc0008d1a00, 0x442e31, 0xc0009d0068, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/rs/rules.go:34 +0x1e2
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls.NewCurrentListener(0xc0008d1a88, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls/listener.go:93 +0x7d
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls.NewCurrentListeners(0xc0008d1cc0, 0xc0008bf408, 0xc000614c20, 0x2, 0x2, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls/listeners.go:61 +0x111
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb.NewCurrentLoadBalancer(0xc0008d1d88, 0xc0004b4240, 0x4, 0xc000760620)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb/loadbalancer.go:262 +0x545
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.NewALBIngressFromAWSLoadBalancer(0xc000025e90, 0xc000059f00, 0xc00002a060, 0xc000280688)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingress.go:227 +0x1fa
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.newIngressesFromLoadBalancers.func1.1(0x1ad3100, 0xc00068e6c0, 0x2, 0x0, 0x1, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingresses.go:188 +0xe0
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1(0xc00068e600, 0xc000084c60, 0xc0006ce2c0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:89 +0x196
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:52 +0x53

goroutine 1 [chan receive]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.newIngressesFromLoadBalancers(0xc0006ce280, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingresses.go:205 +0x198
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.AssembleIngressesFromAWS(0xc00045bcc0, 0x1930271, 0x69, 0xc00045bce0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingresses.go:81 +0x2a4
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller.(*ALBController).awsSync(0xc000110630, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/alb.go:256 +0x31a
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller.(*ALBController).Start(0xc000110630)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/alb.go:160 +0x85
main.main()
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/cmd/main.go:117 +0x4fd

goroutine 18 [chan receive]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x2c339e0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog.init.0
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 14 [chan receive]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc00009a5c0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch/mux.go:207 +0x66
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch.NewBroadcaster
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch/mux.go:75 +0xcc

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/home/travis/.gimme/versions/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 77 [select]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1(0xc00068e600, 0xc000084c60, 0xc0006ce2c0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:77 +0x11d
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:52 +0x53

goroutine 30 [select]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc00039bea0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:206 +0x34f
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/util/workqueue.newDelayingQueue
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:54 +0x1ba

goroutine 27 [IO wait]:
internal/poll.runtime_pollWait(0x7f4f55b72f00, 0x72, 0xc00033c870)
	/home/travis/.gimme/versions/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00049d098, 0x72, 0xffffffffffffff00, 0x1ab3d00, 0x2bd44f0)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00049d098, 0xc00034b000, 0x1000, 0x1000)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc00049d080, 0xc00034b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc00049d080, 0xc00034b000, 0x1000, 0x1000 
```
I was fully aware of this change not persisting across changes to my Ingress definition but expected that the controller would simply ignore the additional rule. I can reliably reproduce this behavior by adding the redirect rule I described. Happy to provide any additional details if required.

**Comment by anhpham1509** [comment]
I have the same situation as you.
@bigkraig Can we have AWS configuration as a superset of Ingress configurations?

**Comment by bigkraig** [comment]
I'd prefer to add support for other actions as requested in #487 vs breaking consistency between ingress resource and ALB configuration. @akshayks, please join the discussion in #487 if you have any opinions of how you would like to see this configuration done, unfortunately compromises must be made due to the lack of support in the ingress resource spec.
