### ISSUE TITLE
Crash on controller startup (nil pointer dereference)

### ISSUE THREAD

**Issue by PaulMaddox** [kubernetes-sigs/aws-alb-ingress-controller#543]
Ingress controller was originally working, however now just crashes on start.
The only thing I can think of, is that I manually added a redirect rule (HTTP -> HTTPS) on the ALB.

```
-------------------------------------------------------------------------------
AWS ALB Ingress controller
  Release:    1.0-beta.5
  Build:      git-8351be1a
  Repository: https://github.com/kubernetes-sigs/aws-alb-ingress-controller
-------------------------------------------------------------------------------

I0812 19:59:09.389314       1 flags.go:131] Watching for Ingress class: alb
W0812 19:59:09.389998       1 flags.go:149] Environment variable configuration is deprecated, switch to the --cluster-name flag.
W0812 19:59:09.390159       1 flags.go:177] Environment variable configuration is deprecated, switch to the --aws-max-retries flag.
W0812 19:59:09.393054       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0812 19:59:09.394774       1 main.go:159] Creating API client for https://10.100.0.1:443
I0812 19:59:09.412196       1 main.go:203] Running in Kubernetes cluster version v1.10 (v1.10.3) - git (clean) commit 2bba0127d85d5a46ab4b778548be28623b32d0b0 - platform linux/amd64
I0812 19:59:09.413083       1 alb.go:85] ALB resource names will be prefixed with d642dfa0
I0812 19:59:09.423033       1 alb.go:158] Starting AWS ALB Ingress controller
I0812 19:59:09.728617       1 albingresses.go:64] Building list of existing ALBs
I0812 19:59:09.793869       1 albingresses.go:72] Fetching information on 1 ALBs
I0812 19:59:10.053508       1 targetgroups.go:97] spinnaker/spinnaker: Fetching Targets for Target Group arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/d642dfa0-spin-deck-256fe49d4/4f85f81f46eb4c19
I0812 19:59:10.113702       1 targetgroups.go:97] spinnaker/spinnaker: Fetching Targets for Target Group arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/d642dfa0-spin-gate-7304f3912/b0a0f479956ed306
I0812 19:59:10.158088       1 rules.go:26] spinnaker/spinnaker: Fetching Rules for Listener arn:aws:elasticloadbalancing:us-west-2:123456789012:listener/app/d642dfa0-spinnaker-spinnak-12f3/dcf9ad1786eaae55/3f8f60918344f26e
F0812 19:59:10.171996       1 albingresses.go:208] ERROR: Work Unit failed due to a recoverable error: 'runtime error: invalid memory address or nil pointer dereference'
, Stack Trace:
 goroutine 86 [running]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1.1(0xc0008d7f18, 0xc000899200)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:60 +0xbc
panic(0x1683760, 0x2c1cd90)
	/home/travis/.gimme/versions/go/src/runtime/panic.go:513 +0x1b9
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/rs.NewCurrentRules(0xc0008d79d8, 0xc00086b000, 0xc0008d7901, 0x100000000408bd5, 0x17058a0, 0xc000647aa0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/rs/rules.go:34 +0x1e2
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls.NewCurrentListener(0xc0008d7a88, 0xc000647aa0, 0xc0008d7ab0, 0x1276d11)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls/listener.go:93 +0x7d
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls.NewCurrentListeners(0xc0008d7cc0, 0xc00086c688, 0xc00067ada0, 0x2, 0x2, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls/listeners.go:61 +0x111
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb.NewCurrentLoadBalancer(0xc0008d7d88, 0xc0000a0900, 0x8, 0xc0005e2360)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb/loadbalancer.go:262 +0x545
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.NewALBIngressFromAWSLoadBalancer(0xc0008c1e90, 0xc000818f00, 0xc00007bc80, 0xc0000adb88)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingress.go:227 +0x1fa
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.newIngressesFromLoadBalancers.func1.1(0x1ad3100, 0xc00076ef60, 0x2, 0x0, 0x454778514c634101, 0x31524e6770625949)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingresses.go:188 +0xe0
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1(0xc00076ef00, 0xc0008ca840, 0xc000899200)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:89 +0x196
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:52 +0x53

goroutine 1 [chan receive]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.newIngressesFromLoadBalancers(0xc0008991c0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingresses.go:205 +0x198
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.AssembleIngressesFromAWS(0xc000187cc0, 0x1930271, 0x69, 0xc000187ce0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingresses.go:81 +0x2a4
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller.(*ALBController).awsSync(0xc0000f26e0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/alb.go:256 +0x31a
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller.(*ALBController).Start(0xc0000f26e0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/alb.go:160 +0x85
main.main()
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/cmd/main.go:117 +0x4fd

goroutine 5 [chan receive]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x2c339e0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog.init.0
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 21 [IO wait]:
internal/poll.runtime_pollWait(0x7f1e906baf00, 0x72, 0xc000392870)
	/home/travis/.gimme/versions/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc0003ce998, 0x72, 0xffffffffffffff00, 0x1ab3d00, 0x2bd44f0)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc0003ce998, 0xc000246000, 0x800, 0x800)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc0003ce980, 0xc000246000, 0x800, 0x800, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc0003ce980, 0xc000246000, 0x800, 0x800, 0x408a0b, 0xc00002e000, 0x16a92e0)
	/home/travis/.gimme/versions/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000c008, 0xc000246000, 0x800, 0x800, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/net/net.go:177 +0x68
crypto/tls.(*block).readFromUntil(0xc000490120, 0x1ab2420, 0xc00000c008, 0x5, 0xc00000c008, 0x0)
	/home/travis/.gimme/versions/go/src/crypto/tls/conn.go:492 +0x89
crypto/tls.(*Conn).readRecord(0xc00005ce00, 0x1965517, 0xc00005cf20, 0x0)
	/home/travis/.gimme/versions/go/src/crypto/tls/conn.go:593 +0xdd
crypto/tls.(*Conn).Read(0xc00005ce00, 0xc00047c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/crypto/tls/conn.go:1145 +0xf1
bufio.(*Reader).Read(0xc00039a2a0, 0xc00030a2d8, 0x9, 0x9, 0xc00005c380, 0xc000392c58, 0xc000392c70)
	/home/travis/.gimme/versions/go/src/bufio/bufio.go:216 +0x22f
io.ReadAtLeast(0x1ab0b40, 0xc00039a2a0, 0xc00030a2d8, 0x9, 0x9, 0x9, 0xc000392cf8, 0x8057cb, 0xc00039a5a0)
	/home/travis/.gimme/versions/go/src/io/io.go:310 +0x88
io.ReadFull(0x1ab0b40, 0xc00039a2a0, 0xc00030a2d8, 0x9, 0x9, 0xc000392d28, 0x8056dd, 0xc000392fb8)
	/home/travis/.gimme/versions/go/src/io/io.go:329 +0x58
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2.readFrameHeader(0xc00030a2d8, 0x9, 0x9, 0x1ab0b40, 0xc00039a2a0, 0x0, 0x0, 0xc000490b70, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc00030a2a0, 0xc000490b70, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2/frame.go:492 +0xa3
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000392fb8, 0x1964478, 0xc00005a7b8)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aw
```

**Comment by bigkraig** [comment]
That’s expected, work on customized actions is in #542 if you would like to test them out.

**Comment by bigkraig** [comment]
Resolved in `1.0-beta.6`

**Comment by stevenpall** [comment]
@bigkraig Should I open a new issue for this ^?

**Comment by bigkraig** [comment]
Yes please @stevenpall
