### ISSUE TITLE
Multi-path issue

### ISSUE THREAD

**Issue by lemonshow** [kubernetes-sigs/aws-alb-ingress-controller#552]
It seems the multi-path mapping does not work as expected.
Only the /newpath/ works but not the /. Do we support target rewrite?

spec:
  rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: serviceA
            servicePort: 80
        - path: /newpath/
          backend:
            serviceName: serviceB
            servicePort: 80

**Comment by bigkraig** [comment]
ALBs do not support target rewrite, you may also need to use wildcards to achieve whatever you are doing, or re-order the rules due to how ALBs match path patterns. Best thing to do is check out the AWS docs on how the rules are implemented.

**Comment by lemonshow** [comment]
Thanks, reorder and with wild card make the two paths work. 
However the default path is taken from the first one only. Defining a default backend seems not taking effect.

spec:
  #backend:
  #  serviceName: serviceA
  #  servicePort: 80
  rules:
    - http:
        paths:
        - path: /newpath/*
          backend:
            serviceName: serviceB
            servicePort: 80
        - path: /*
          backend:
            serviceName: serviceA
            servicePort: 80

**Comment by bigkraig** [comment]
Are you running `1.0-beta.6`?

**Comment by lemonshow** [comment]
Got a chance to try and beta6 works for default.

**Comment by lemonshow** [comment]
I am hitting a random recoverable error when I checked the log after a few deployments. Not able to see it again though.
```
I0819 00:32:41.944687       1 targetgroup.go:221] local/ysun-xxx--ingress: Start TargetGroup creation.
I0819 00:32:41.944868       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"ysun-xxx--ingress", UID:"12344-a347-11e8-b350-025b36c7c844", APIVersion:"extensions/v1beta1", ResourceVersion:"170337", FieldPath:""}): type: 'Normal' reason: 'CREATE' 12345-b5438c7cc346a490312 target group created
I0819 00:32:42.389735       1 targetgroup.go:226] local/ysun-testeksapp--ingress: Succeeded TargetGroup creation. ARN: arn:aws:elasticloadbalancing:us-west-2:111111:targetgroup/974d7361-11111/11111 | Name: 11111-2222222222.
I0819 00:32:42.389764       1 listener.go:195] local/ysun-xxx--ingress: Start Listener creation.
I0819 00:32:42.390022       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"local", Name:"ysun-xxxx--ingress", UID:"111111-a347-11e8-b350-222222", APIVersion:"extensions/v1beta1", ResourceVersion:"170337", FieldPath:""}): type: 'Normal' reason: 'CREATE' 974d7361-8d2715cc1111111111 target group created
F0819 00:32:42.415118       1 albingresses.go:167] ERROR: Work Unit failed due to a recoverable error: 'runtime error: invalid memory address or nil pointer dereference'
, Stack Trace:
 goroutine 182959 [running]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1.1(0xc000bd9f18, 0xc000959040)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:60 +0xbc
panic(0x1687b00, 0x2c25d90)
	/home/travis/.gimme/versions/go/src/runtime/panic.go:513 +0x1b9
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls.(*Listener).DefaultActionArn(...)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls/listener.go:329
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb.(*LoadBalancer).Reconcile(0xc00010f760, 0xc000bd9e30, 0xc0006a12b8, 0x10, 0x10)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb/loadbalancer.go:314 +0x405
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.(*ALBIngress).Reconcile(0xc0000dc780, 0xc0009cbea8, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingress.go:281 +0x12e
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.ALBIngresses.Reconcile.func1.1(0x1ad8720, 0xc0009194a0, 0x2, 0x0, 0xc0004fc501, 0x1742fa0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingresses.go:154 +0xce
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1(0xc000919440, 0xc0004fc540, 0xc000959040)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:89 +0x196
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:52 +0x53

goroutine 1 [select, 1 minutes]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller.(*ALBController).Start(0xc00043a6e0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/alb.go:193 +0x3ff
main.main()
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/cmd/main.go:117 +0x4fd

goroutine 18 [chan receive, 1 minutes]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x2c3c9a0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog.init.0
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 33 [syscall, 1497 minutes]:
os/signal.signal_recv(0x0)
	/home/travis/.gimme/versions/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 27 [chan receive, 1497 minutes]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache.(*sharedProcessor).run(0xc0001a5650, 0xc000096840)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache/shared_informer.go:425 +0x46
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache.(*sharedProcessor).run-fm(0xc000096840)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache/shared_informer.go:220 +0x34
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:54 +0x2e
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0004291d0, 0xc000423000)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62

goroutine 28 [chan receive, 1497 minutes]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache.(*controller).Run.func1(0xc0000d6300, 0xc00042a580)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache/controller.go:103 +0x34
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache.(*controller).Run
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache/controller.go:102 +0x92

goroutine 15 [runnable]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc000424580)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch/mux.go:207 +0x66
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch.NewBroadcaster
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch/mux.go:75 +0xcc

goroutine 9 [IO wait]:
internal/poll.runtime_pollWait(0x7fbe214aaf00, 0x72, 0xc0000ba870)
	/home/travis/.gimme/versions/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00042a518, 0x72, 0xffffffffffffff00, 0x1ab9320, 0x2bdd4f0)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00042a518, 0xc0005bc000, 0x4000, 0x4000)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc00042a500, 0xc0005bc000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc00042a500, 0xc0005bc000, 0x4000, 0x4000, 0x408a0b, 0xc00002e000, 0x16ad700)
	/home/travis/.gimme/versions/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000a6018, 0xc0005bc000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/net/net.go:177 +0x68
crypto/tls.(*block).readFromUntil(0xc000418540, 0x1ab7a00, 0xc0000a6018, 0x5, 0xc0000a6018, 0x0)
	/home/travis/.gimme/versions/go/src/crypto/tls/conn.go:492 +0x89
crypto/tls.(*Conn).readRecord(0xc00007a700, 0x196a417, 0xc00007a820, 0xc000187c00)
	/home/travis/.gimme/versio

**Comment by M00nF1sh** [comment]
@lemonshow 
Is this still an issue?

in our new beta.7, the default backend will be 404(instead of first rule) if you don't specify default backend.

Also, The ingress spec didn't specify the current semantic of priority among list of rules, but in sensible manner, it should be `match the first rule` by follow the order specified by user.(which is what we did currently).
On the other hand, it's impossible for the controller to order rules on customer behalf. e.g. two rule `/*/f1sh`, `/m00n/*`.

So customers should organize the rule themself.

**Comment by lemonshow** [comment]
Tried beta.7, we do specify default and can see it takes the path.

**Comment by lemonshow** [comment]
Related issue we see for,
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/575

**Comment by M00nF1sh** [comment]
@lemonshow 
I'll close this since it's not an issue. Let's continue discussion in  #135 .

For now, can you share the same path for all ports?
Since ingress spec doesn't support different path by port, supporting it will make AWS ingress spec diverge from k8s.
An alternative better solution should be reuse same alb among multiple ingresses, so that you can put your special listener port into another ingress resource, but share the same alb with ingress with regular ports

**Comment by lemonshow** [comment]
Yes, we can close this.

**Comment by lemonshow** [comment]
For now, we do share the same path for all ports.
