### ISSUE TITLE
Panic on start from Reconcile, FindUnusedTGs

### ISSUE THREAD

**Issue by krmcbride** [kubernetes-sigs/aws-alb-ingress-controller#568]
I'm no gopher so I'm not sure if I'm reading this correctly but my guess is its bailing on Actions that don't forward to a TG, like the ones I've defined with fixed responses.

```
-------------------------------------------------------------------------------
AWS ALB Ingress controller
  Release:    1.0-beta.6
  Build:      git-f740c293
  Repository: https://github.com/kubernetes-sigs/aws-alb-ingress-controller
-------------------------------------------------------------------------------

I0816 21:21:32.471250       1 main.go:203] Running in Kubernetes cluster version v1.10 (v1.10.3) - git (clean) commit 2bba0127d85d5a46ab4b778548be28623b32d0b0 - platform linux/amd64
I0816 21:21:32.471806       1 alb.go:85] ALB resource names will be prefixed with 9c20ce57
I0816 21:21:32.482233       1 alb.go:158] Starting AWS ALB Ingress controller
I0816 21:21:33.682618       1 leaderelection.go:185] attempting to acquire leader lease  kube-system/ingress-controller-leader-alb...
I0816 21:21:33.694446       1 leaderelection.go:194] successfully acquired lease kube-system/ingress-controller-leader-alb
I0816 21:21:33.694477       1 status.go:152] new leader elected: alb-ingress-controller-ccd4dd4f5-njcb5
I0816 21:21:34.541368       1 albingresses.go:77] Building list of existing ALBs
I0816 21:21:34.656723       1 albingresses.go:85] Fetching information on 1 ALBs
I0816 21:21:34.966219       1 targetgroup.go:176] dev1/alb-ingress-internal: Fetching Targets for Target Group arn:aws:elasticloadbalancing:us-west-2:123:targetgroup/9c20ce57-3f92aca12aa2e548a59/ee53551973282eb9
I0816 21:21:35.018601       1 rules.go:29] dev1/alb-ingress-internal: Fetching Rules for Listener arn:aws:elasticloadbalancing:us-west-2:123:listener/app/9c20ce57-dev1-albingressi-d7ce/f3710bb857d17983/4b4bd1c2d7e83e59
I0816 21:21:35.039900       1 albingress.go:230] dev1/alb-ingress-internal: Ingress rebuilt from existing ALB in AWS
I0816 21:21:35.039931       1 albingresses.go:101] Assembled 1 ingresses from existing AWS resources in 498.543804ms
F0816 21:21:35.982527       1 albingresses.go:167] ERROR: Work Unit failed due to a recoverable error: 'runtime error: invalid memory address or nil pointer dereference'
, Stack Trace:
 goroutine 384 [running]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1.1(0xc000a71f18, 0xc000ac6100)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:60 +0xbc
panic(0x1687b00, 0x2c25d90)
        /home/travis/.gimme/versions/go/src/runtime/panic.go:513 +0x1b9
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/rs.Rules.FindUnusedTGs(0xc000ac6180, 0x7, 0x8, 0xc000608090, 0x1, 0x1, 0x0, 0x0, 0x0, 0x60)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/rs/rules.go:190 +0xa4
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb.(*LoadBalancer).Reconcile(0xc000b07a20, 0xc000a71e30, 0xc0009c8f38, 0x10, 0x10)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb/loadbalancer.go:314 +0x38a
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.(*ALBIngress).Reconcile(0xc00045c480, 0xc0002e76a8, 0x0, 0x0)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingress.go:281 +0x12e
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.ALBIngresses.Reconcile.func1.1(0x1ad8720, 0xc000acac60, 0x2, 0x0, 0xc000022801, 0xc0002e7718)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingresses.go:154 +0xce
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1(0xc000acac00, 0xc000022840, 0xc000ac6100)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:89 +0x196
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:52 +0x53

goroutine 1 [select]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller.(*ALBController).Start(0xc000438a50)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/alb.go:193 +0x3ff
main.main()
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/cmd/main.go:117 +0x4fd

goroutine 5 [chan receive]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x2c3c9a0)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog.init.0
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 33 [syscall]:
os/signal.signal_recv(0x0)
        /home/travis/.gimme/versions/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 40 [IO wait]:
internal/poll.runtime_pollWait(0x7ff538b72f00, 0x72, 0xc0000aa870)
        /home/travis/.gimme/versions/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000516d18, 0x72, 0xffffffffffffff00, 0x1ab9320, 0x2bdd4f0)
        /home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000516d18, 0xc00062e000, 0x8000, 0x8000)
        /home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000516d00, 0xc00062e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000516d00, 0xc00062e000, 0x8000, 0x8000, 0x408a0b, 0xc00002e000, 0x16ad700)
        /home/travis/.gimme/versions/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000c6f8, 0xc00062e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/net/net.go:177 +0x68
crypto/tls.(*block).readFromUntil(0xc0004e5b00, 0x1ab7a00, 0xc00000c6f8, 0x5, 0xc00000c6f8, 0x0)
        /home/travis/.gimme/versions/go/src/crypto/tls/conn.go:492 +0x89
crypto/tls.(*Conn).readRecord(0xc000470700, 0x196a417, 0xc000470820, 0x0)
        /home/travis/.gimme/versions/go/src/crypto/tls/conn.go:593 +0xdd
crypto/tls.(*Conn).Read(0xc000470700, 0xc0003de000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/crypto/tls/conn.go:1145 +0xf1
bufio.(*Reader).Read(0xc00008a480, 0xc0003922d8, 0x9, 0x9, 0x28, 0x42df0c, 0xc0000aac50)
        /home/travis/.gimme/versions/go/src/bufio/bufio.go:216 +0x22f
io.ReadAtLeast(0x1ab60e0, 0xc00008a480, 0xc0003922d8, 0x9, 0x9, 0x9, 0x196a400, 0xc0000aacf0, 0xc0000aace0)
        /home/travis/.gimme/versions/go/src/io/io.go:310 +0x88
io.ReadFull(0x1ab60e0, 0xc00008a480, 0xc0003922d8, 0x9, 0x9, 0xc000504000, 0x1d5, 0x4000)
        /home/travis/.gimme/versions/go/src/io/io.go:329 +0x58
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2.readFrameHeader(0xc0003922d8, 0x9, 0x9, 0x1ab60e0, 0xc00008a480, 0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc0003922a0, 0xc000419620, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2/frame.go:492 +0xa3
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc0000aafb8, 0x1969290, 0xc0004367b8)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2/transport.go:1616 +0x9e
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc000448540)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2/transport.go:1544 +0x76
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2.(*Transport).newClientConn
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2/transport.go:619 +0x636

goroutine 59 [chan receive]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x42b2d3, 0xc000430dc8, 0x3)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache/shared_informer.go:549 +0x54
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x
```

Simplified ingress:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alb-ingress-internal
  namespace: dev1
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:us-west-2:123:certificate/123'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/security-groups: sg-abc
    alb.ingress.kubernetes.io/actions.fixed-response-error: >-
      {"Type": "fixed-response", "FixedResponseConfig": {"ContentType":"text/plain", 
      "StatusCode":"403", "MessageBody":"Forbidden"}}
spec:
  rules:
  - host: foo.example.com
    http:
      paths:
      - path: /nope*
        backend:
          serviceName: fixed-response-error
          servicePort: use-annotation
      - path: /*
        backend:
          serviceName: myapp
          servicePort: 80
```

Maybe my ingress is weird, but it seems to produce the expected rules.

**Comment by tobiasrosenhoff** [comment]
I'm getting the same error when using **servicePort: use-annotation** with "Type": "redirect"

**Comment by M00nF1sh** [comment]
@krmcbride 
Hi Kevin
Sorry for the late update. I believe this issue is solve by our new release `quay.io/coreos/alb-ingress-controller:1.0-beta.7`. 
And i just verified it with your testcase  😄
