### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by cjbottaro** [kubernetes-sigs/aws-alb-ingress-controller#578]
```
$ kubectl logs -n kube-system alb-ingress-controller-6bcdb846cb-kcvc2
-------------------------------------------------------------------------------
AWS ALB Ingress controller
  Release:    1.0-beta.6
  Build:      git-734cbf15
  Repository: https://github.com/kubernetes-sigs/aws-alb-ingress-controller
-------------------------------------------------------------------------------

W0828 03:08:17.900416       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0828 03:08:17.900656       1 main.go:159] Creating API client for https://10.3.0.1:443
I0828 03:08:17.919034       1 main.go:203] Running in Kubernetes cluster version v1.11 (v1.11.2) - git (clean) commit bb9ffb1654d4a729bb4cec18ff088eacc153c239 - platform linux/amd64
I0828 03:08:17.919874       1 alb.go:85] ALB resource names will be prefixed with d334b68c
I0828 03:08:17.926679       1 alb.go:158] Starting AWS ALB Ingress controller
I0828 03:08:19.127355       1 leaderelection.go:185] attempting to acquire leader lease  kube-system/ingress-controller-leader-alb...
I0828 03:08:19.140997       1 leaderelection.go:194] successfully acquired lease kube-system/ingress-controller-leader-alb
I0828 03:08:19.141028       1 status.go:152] new leader elected: alb-ingress-controller-6bcdb846cb-kcvc2
I0828 03:08:19.481614       1 albingresses.go:77] Building list of existing ALBs
I0828 03:08:19.722246       1 albingresses.go:85] Fetching information on 2 ALBs
I0828 03:08:19.969106       1 targetgroup.go:176] default/engineering-app: Fetching Targets for Target Group arn:aws:elasticloadbalancing:us-east-1:853401350379:targetgroup/d334b68c-738f1510e62595ad48f/7f74c4ceff327052
I0828 03:08:20.003986       1 targetgroup.go:176] default/ssl: Fetching Targets for Target Group arn:aws:elasticloadbalancing:us-east-1:853401350379:targetgroup/d334b68c-0139c52a5f6ec060766/1c589a85ff7c8b4b
I0828 03:08:20.032297       1 targetgroup.go:176] default/engineering-app: Fetching Targets for Target Group arn:aws:elasticloadbalancing:us-east-1:853401350379:targetgroup/d334b68c-9a1a1503dd3e5e61aea/4df7fdfd09653b9a
I0828 03:08:20.043296       1 rules.go:29] default/ssl: Fetching Rules for Listener arn:aws:elasticloadbalancing:us-east-1:853401350379:listener/app/d334b68c-default-ssl-e531/a0a7201c680d3c44/ed4d963be42fcc8c
I0828 03:08:20.056845       1 albingress.go:230] default/ssl: Ingress rebuilt from existing ALB in AWS
I0828 03:08:20.075648       1 targetgroup.go:176] default/engineering-app: Fetching Targets for Target Group arn:aws:elasticloadbalancing:us-east-1:853401350379:targetgroup/d334b68c-c384a1a1f1e7dfcac44/a52b3506b3966f95
I0828 03:08:20.142662       1 targetgroup.go:176] default/engineering-app: Fetching Targets for Target Group arn:aws:elasticloadbalancing:us-east-1:853401350379:targetgroup/d334b68c-e019a7f77c5c3cbddde/702d06adbc08cd75
I0828 03:08:20.210950       1 rules.go:29] default/engineering-app: Fetching Rules for Listener arn:aws:elasticloadbalancing:us-east-1:853401350379:listener/app/d334b68c-default-engineeri-b73e/58c5f4be7edbbdeb/dde391b1974353f8
I0828 03:08:20.236598       1 albingress.go:230] default/engineering-app: Ingress rebuilt from existing ALB in AWS
I0828 03:08:20.236637       1 albingresses.go:101] Assembled 2 ingresses from existing AWS resources in 754.99981ms
E0828 03:08:20.402867       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:522
/home/travis/.gimme/versions/go/src/runtime/panic.go:513
/home/travis/.gimme/versions/go/src/runtime/panic.go:82
/home/travis/.gimme/versions/go/src/runtime/signal_unix.go:390
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/tg/targetgroups.go:118
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb/loadbalancer.go:108
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingress.go:141
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingresses.go:48
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/controller.go:35
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/alb.go:105
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/task/queue.go:129
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/task/queue.go:61
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/task/queue.go:61
/home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:1333
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x137b753]

goroutine 119 [running]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x168cd40, 0x2c2bd90)
	/home/travis/.gimme/versions/go/src/runtime/panic.go:513 +0x1b9
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/tg.NewDesiredTargetGroups(0xc0004c9958, 0x2c60e40, 0x0, 0x0, 0x1, 0xc000c60d70)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/tg/targetgroups.go:118 +0x1b3
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb.NewDesiredLoadBalancer(0xc0004c9ad8, 0xc000494000, 0x3, 0x4)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb/loadbalancer.go:108 +0x69d
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.NewALBIngressFromIngress(0xc0004c9c28, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingress.go:141 +0x471
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.NewALBIngressesFromIngresses(0xc0004c9ce0, 0x196d500, 0xc0004562c0, 0xc0005c7cc0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingresses.go:48 +0x1d6
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller.(*ALBController).syncIngress(0xc0004562c0, 0x1762100, 0xc000269e60, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/controller.go:35 +0x18f
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller.(*ALBController).syncIngress-fm(0x1762100, 0xc000269e60, 0xa, 0xc0005c7dd0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/alb.go:105 +0x3e
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/task.(*Queue).worker(0xc0003d0a20)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/task/queue.go:129 +0x2de
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/task.(*Queue).worker-fm()
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/task/queue.go:61 +0x2a
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00005cfa8)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0004c9fa8, 0x3b9aca00, 0x0, 0xc00012f201, 0xc000480360)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00005cfa8, 0x3b9aca00, 0xc000480360)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/task.(*Queue).Run(0xc0003d0a20, 0x3b9aca00, 0xc000480360)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/task/queue.go:61 +0x5d
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller.(*ALBController).Start
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/alb.go:166 +0xe1
```

Let me know what other info I need to provide. Thanks.

**Comment by cjbottaro** [comment]
I think this was due to me having a rule with just a host and no path.
