### ISSUE TITLE
controller panic crash following an error to create TargetGroup

### ISSUE THREAD

**Issue by neerfri** [kubernetes-sigs/aws-alb-ingress-controller#579]
Using alb-ingress-controller `v1.0-beta.6` crashed trying to create an ingress with `target-type: ip` .
See crash log and ingress resource below.

I believe this is somewhat similar to #572 but the crash is not mentioned there. In fact he shows more log lines after the failure so this could be a different situation.

```
-------------------------------------------------------------------------------
AWS ALB Ingress controller
  Release:    1.0-beta.6
  Build:      git-f740c293
  Repository: https://github.com/kubernetes-sigs/aws-alb-ingress-controller
-------------------------------------------------------------------------------

I0829 08:44:08.424180       1 flags.go:132] Watching for Ingress class: alb
W0829 08:44:08.424320       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0829 08:44:08.424488       1 main.go:159] Creating API client for https://10.100.0.1:443
I0829 08:44:08.520374       1 main.go:203] Running in Kubernetes cluster version v1.10 (v1.10.3) - git (clean) commit 2bba0127d85d5a46ab4b778548be28623b32d0b0 - platform linux/amd64
I0829 08:44:08.521139       1 alb.go:85] ALB resource names will be prefixed with 723b14ae
I0829 08:44:08.531658       1 alb.go:158] Starting AWS ALB Ingress controller
I0829 08:44:10.332022       1 leaderelection.go:185] attempting to acquire leader lease  kube-system/ingress-controller-leader-alb...
I0829 08:44:10.337029       1 status.go:152] new leader elected: alb-ingress-controller-f99f9df45-lkkhw
I0829 08:44:11.211968       1 albingresses.go:77] Building list of existing ALBs
I0829 08:44:11.264339       1 albingresses.go:85] Fetching information on 0 ALBs
I0829 08:44:11.333315       1 albingresses.go:101] Assembled 0 ingresses from existing AWS resources in 121.326015ms
I0829 08:44:51.370007       1 loadbalancer.go:265] my-namespace/my-ingress: Start ELBV2 creation.
I0829 08:44:51.977262       1 loadbalancer.go:272] my-namespace/my-ingress: Completed ELBV2 creation. Name: 723b14ae-my-namespace-my-i-2fa4 | ARN: arn:aws:elasticloadbalancing:us-east-1:111111111111:loadbalancer/app/723b14ae-my-namespace-my-i-2fa4/095313d9e38ac3a1
I0829 08:44:51.977279       1 targetgroup.go:221] my-namespace/my-ingress: Start TargetGroup creation.
I0829 08:44:51.977335       1 listener.go:195] my-namespace/my-ingress: Start Listener creation.
I0829 08:44:51.977445       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"my-namespace", Name:"my-ingress", UID:"cafd0cd0-ab67-11e8-81f3-0a04f9bf66e0", APIVersion:"extensions/v1beta1", ResourceVersion:"9170859", FieldPath:""}): type: 'Normal' reason: 'CREATE' 723b14ae-my-namespace-my-i-2fa4 created
I0829 08:44:51.977490       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"my-namespace", Name:"my-ingress", UID:"cafd0cd0-ab67-11e8-81f3-0a04f9bf66e0", APIVersion:"extensions/v1beta1", ResourceVersion:"9170859", FieldPath:""}): type: 'Warning' reason: 'ERROR' Error creating target group 723b14ae-d36afe889fc27b21820: InvalidParameter: 1 validation error(s) found.
- minimum field value of 1, CreateTargetGroupInput.Port.
I0829 08:44:51.987337       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"my-namespace", Name:"my-ingress", UID:"cafd0cd0-ab67-11e8-81f3-0a04f9bf66e0", APIVersion:"extensions/v1beta1", ResourceVersion:"9170859", FieldPath:""}): type: 'Warning' reason: 'ERROR' Error creating 443 listener: ValidationError: A target group ARN must be specified
	status code: 400, request id: cb8cbead-ab67-11e8-a9b0-757eb555619d
F0829 08:44:51.987355       1 albingresses.go:167] ERROR: Work Unit failed due to a recoverable error: 'runtime error: invalid memory address or nil pointer dereference'
, Stack Trace:
 goroutine 425 [running]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1.1(0xc0008d1f18, 0xc00214a600)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:60 +0xbc
panic(0x1687b00, 0x2c25d90)
	/home/travis/.gimme/versions/go/src/runtime/panic.go:513 +0x1b9
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls.(*Listener).DefaultActionArn(...)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls/listener.go:329
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb.(*LoadBalancer).Reconcile(0xc00214c160, 0xc0008d1e30, 0xc001eb1a48, 0x10, 0x10)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb/loadbalancer.go:314 +0x405
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.(*ALBIngress).Reconcile(0xc0001b0000, 0xc000e72ea8, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingress.go:281 +0x12e
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.ALBIngresses.Reconcile.func1.1(0x1ad8720, 0xc0020f6480, 0x2, 0x0, 0x36622f5053313501, 0x6576396c64444b46)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingresses.go:154 +0xce
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1(0xc0020f6420, 0xc000580840, 0xc00214a600)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:89 +0x196
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:52 +0x53

goroutine 1 [select]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller.(*ALBController).Start(0xc0002cc630)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/alb.go:193 +0x3ff
main.main()
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/cmd/main.go:117 +0x4fd

goroutine 18 [chan receive]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x2c3c9a0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog.init.0
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 33 [syscall]:
os/signal.signal_recv(0x0)
	/home/travis/.gimme/versions/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 47 [chan receive]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache.(*controller).Run.func1(0xc0002ba120, 0xc000574000)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache/controller.go:103 +0x34
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache.(*controller).Run
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache/controller.go:102 +0x92

goroutine 82 [select]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc0004550e0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:206 +0x34f
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/util/workqueue.newDelayingQueue
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:54 +0x1ba

goroutine 46 [chan receive]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache.(*sharedProcessor).run(0xc0001c9dc0, 0xc000580000)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache/shared_informer.go:425 +0x46
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache.(*sharedProcessor).run-fm(0xc000580000)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache/shared_informer.go:220 +0x34
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:54 +0x2e
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc00058e000, 0xc000508b00)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62

goroutine 39 [IO wait]:
internal/poll.runtime_pollWait(0x7f9329a2ff00, 0x72, 0xc00013e870)
	/home/travis/.gimme/versions/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000146a98, 0x72, 0xffffffffffffff00, 0x1ab9320, 0x2bdd4f0)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000146a98, 0xc0004a4000, 0x8000, 0x8000)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000146a80, 0xc0004a4000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000146a80, 0xc0004a4000, 0x8000, 0x8000, 0x408a0b, 0xc00002e000, 0x16ad700)
	/home/travis/.gimme/versions/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00050a008, 0xc0004a4000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/net/net.go:177 +0x68
crypto/tls.(*block).readFromUntil(0xc00027ac00, 0x1ab7a00, 0xc00050a008, 0x5, 0xc00050a008, 0x0)
	/home/travis/.gimme/versions/go/src/crypto/tls/conn.go:492 +0x89
crypto/tls.(*Conn).readRecord(0xc000094380, 0x196a417, 0xc0000944a0, 0x0)
	/home/travis/.gimme/versions/go/src/crypto/tls
```

The `Ingress` resource YAML:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  namespace: my-namespace
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:123:certificate/111111-2222-333-4444-5555555
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/security-groups: sg-1111111,sg-222222
  labels:
    app: applicaster2
    component: web
spec:
  rules:
    - host: admin.applicaster.com
      http:
        paths:
          - path: /
            backend:
              serviceName: applicaster2
              servicePort: 80
```

**Comment by neerfri** [comment]
@bigkraig I believe this should be labeled `kind/bug` and added to the `1.0` milestone

**Comment by akshayks** [comment]
@neerfri I forgot to mention that the controller was continually crashing. This issue appears to the same as the one I reported.

**Comment by M00nF1sh** [comment]
should be same as https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/572, 
root cause found but pending confirm 😃
