### ISSUE TITLE
panic when removing action annotation but leaving paths

### ISSUE THREAD

**Issue by natefox** [kubernetes-sigs/aws-alb-ingress-controller#591]
This is 100% a UX request as the true problem is a misconfiguration. However, I think throwing a readable error would be preferable to the crash :)

Using the sample ingress from the helm chart installation, I've added the fixed-response actions annotation and the path rule. This works.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/security-groups: sg-005692ccd355680ae
    alb.ingress.kubernetes.io/subnets: subnet-05a535ccd4f2b011c,subnet-095f006cb178d7abc,subnet-0c4d71e0c2fc6a12c
    # alb.ingress.kubernetes.io/actions.fixed-response-error: '{"Type": "fixed-response", "FixedResponseConfig": {"ContentType":"text/plain", "StatusCode":"503", "MessageBody":"503 error text"}}'
  name: example
spec:
  rules:
    - host: www.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: my-sample-service
              servicePort: 80
          - path: /x503
            backend:
              serviceName: fixed-response-error
              servicePort: use-annotation
```

When I comment out the action annotation and do not comment out the path rule (as seen above), I get the following panic. Controller continues to panic as long as the annotation is not there while the rule remains.

```
-------------------------------------------------------------------------------
AWS ALB Ingress controller
  Release:    1.0-beta.6
  Build:      git-f740c293
  Repository: https://github.com/kubernetes-sigs/aws-alb-ingress-controller
-------------------------------------------------------------------------------

I0906 23:05:07.290728       1 flags.go:132] Watching for Ingress class: alb
W0906 23:05:07.290904       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0906 23:05:07.291113       1 main.go:159] Creating API client for https://10.100.0.1:443
I0906 23:05:07.307895       1 main.go:203] Running in Kubernetes cluster version v1.10 (v1.10.3) - git (clean) commit 2bba0127d85d5a46ab4b778548be28623b32d0b0 - platform linux/amd64
I0906 23:05:07.308784       1 alb.go:85] ALB resource names will be prefixed with 655061ae
I0906 23:05:07.316168       1 alb.go:158] Starting AWS ALB Ingress controller
I0906 23:05:08.517511       1 leaderelection.go:185] attempting to acquire leader lease  opssuite/ingress-controller-leader-alb...
I0906 23:05:08.523929       1 leaderelection.go:194] successfully acquired lease opssuite/ingress-controller-leader-alb
I0906 23:05:08.523940       1 status.go:152] new leader elected: funny-hog-alb-ingress-controller-controller-747cb76c98-jkpv8
I0906 23:05:08.660585       1 albingresses.go:77] Building list of existing ALBs
I0906 23:05:08.706232       1 albingresses.go:85] Fetching information on 1 ALBs
I0906 23:05:08.908268       1 targetgroup.go:176] opssuite/example: Fetching Targets for Target Group arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/655061ae-d3788115ac87f4fcc58/8029f8d350167df1
I0906 23:05:08.966253       1 rules.go:29] opssuite/example: Fetching Rules for Listener arn:aws:elasticloadbalancing:us-west-2:123456789012:listener/app/655061ae-opssuite-example-7c81/268b9e36cd40ab99/0f6d60a5bcfa2225
I0906 23:05:08.984045       1 albingress.go:230] opssuite/example: Ingress rebuilt from existing ALB in AWS
I0906 23:05:08.984076       1 albingresses.go:101] Assembled 1 ingresses from existing AWS resources in 323.470287ms
E0906 23:05:09.118426       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:522
/home/travis/.gimme/versions/go/src/runtime/panic.go:513
/home/travis/.gimme/versions/go/src/runtime/panic.go:82
/home/travis/.gimme/versions/go/src/runtime/signal_unix.go:390
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/rs/rule.go:62
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/rs/rules.go:104
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls/listener.go:72
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls/listeners.go:107
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb/loadbalancer.go:122
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingress.go:141
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingresses.go:48
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/controller.go:35
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/alb.go:105
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/task/queue.go:129
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/task/queue.go:61
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/task/queue.go:61
/home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:1333
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1377b78]

goroutine 106 [running]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x1687b00, 0x2c25d90)
	/home/travis/.gimme/versions/go/src/runtime/panic.go:513 +0x1b9
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/rs.NewDesiredRule(0xc000285950, 0xc000285950, 0xe, 0xc0002858c0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/rs/rule.go:62 +0x778
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/rs.NewDesiredRules(0xc0002d76f0, 0xc000731d20, 0x1896a60, 0xc0000e8640, 0xc000744201, 0x0, 0xc0002d7728)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/rs/rules.go:104 +0x44d
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls.NewDesiredListener(0xc000178930, 0xc000178930, 0x10, 0xc0000e8640)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls/listener.go:72 +0x414
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls.NewDesiredListeners(0xc0002d7900, 0xc00078cdf0, 0x2, 0x2, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls/listeners.go:107 +0x251
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb.NewDesiredLoadBalancer(0xc0002d7ad8, 0xc000484000, 0x3, 0x4)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb/loadbalancer.go:122 +0x7e2
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.NewALBIngressFromIngress(0xc0004d1c28, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingress.go:141 +0x471
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.NewALBIngressesFromIngresses(0xc0002d7ce0, 0x1967db8, 0xc000171810, 0xc0004d1cc0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingresses.go:48 +0x1d6
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller.(*ALBController).syncIngress(0xc000171810, 0x175ca40, 0xc00049f000, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/controller.go:35 +0x18f
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller.(*ALBController).syncIngress-fm(0x175ca40, 0xc00049f000, 0xa, 0xc0004d1dd0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/alb.go:105 +0x3e
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/task.(*Queue).worker(0xc0003fbe60)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/task/queue.go:129 +0x2de
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/task.(*Queue).worker-fm()
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/task/queue.go:61 +0x2a
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0005087a8)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0002d7fa8, 0x3b9aca00, 0x0, 0x1, 0xc000044240)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0005087a8, 0x3b9aca00, 0xc000044240)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/task.(*Queue).Run(0xc0003fbe60, 0x3b9aca00, 0xc000044240)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/task/queue.go:61 +0x5d
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller.(*ALBController).Start
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/alb.go:166 +0xe1
```

**Comment by bigkraig** [comment]
This was resolved in #621
