### ISSUE TITLE
Panic when specifying HTTPS listener but omitting certificate

### ISSUE THREAD

**Issue by cv** [kubernetes-sigs/aws-alb-ingress-controller#594]
I forgot to add a cert reference in my ingress definition, which looks like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-07e12f458bc17f001, subnet-083b60e393ac1a1c2
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":8080,"HTTPS": 443}]'
    kubernetes.io/ingress.class: public-ingress
  name: echoserver
  namespace: echoserver
spec:
  rules:
  - host: echoserver.dev.k8s.cafe
    http:
      paths:
      - backend:
          serviceName: echoserver
          servicePort: 80
        path: /
```

When applied, this caused the alb-ingress-controller to crash:

```
F0907 18:20:04.774426       1 albingresses.go:167] ERROR: Work Unit failed due to a recoverable error: 'runtime error: invalid memory address or nil pointer dereference'
, Stack Trace:
 goroutine 46951 [running]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1.1(0xc00048ff18, 0xc0007a5300)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:60 +0xbc
panic(0x1687b00, 0x2c25d90)
        /home/travis/.gimme/versions/go/src/runtime/panic.go:513 +0x1b9
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls.(*Listener).DefaultActionArn(...)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls/listener.go:329
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb.(*LoadBalancer).Reconcile(0xc0005f7ce0, 0xc00048fe30, 0xc0007974a0, 0x10, 0x10)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb/loadbalancer.go:314 +0x405
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.(*ALBIngress).Reconcile(0xc00041b140, 0xc0004c56a8, 0x0, 0x0)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingress.go:281 +0x12e
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.ALBIngresses.Reconcile.func1.1(0x1ad8720, 0xc0007eb1a0, 0x2, 0x0, 0x16ad601, 0x1742fa0)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingresses.go:154 +0xce
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1(0xc0007eb140, 0xc00041e840, 0xc0007a5300)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:89 +0x196
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:52 +0x53

goroutine 1 [select, 1 minutes]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller.(*ALBController).Start(0xc0003fc580)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/alb.go:193 +0x3ff
main.main()
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/cmd/main.go:117 +0x4fd

goroutine 5 [chan receive, 1 minutes]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x2c3c9a0)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog.init.0
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 18 [syscall, 211 minutes]:
os/signal.signal_recv(0x0)
        /home/travis/.gimme/versions/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 69 [chan receive, 1 minutes]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x42b2d3, 0xc00046fdc8, 0x3)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache/shared_informer.go:549 +0x54
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0xc000588e18, 0x42ade2, 0xc000180fd0)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:203 +0x9c
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache/shared_informer.go:548 +0x89
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00046ff68)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000588f68, 0xdf8475800, 0x0, 0x1645f01, 0xc00041e720)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00046ff68, 0xdf8475800, 0xc00041e720)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc00010f480)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache/shared_informer.go:546 +0x8d
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache.(*processorListener).run-fm()
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/cache/shared_informer.go:390 +0x2a
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000105d40, 0xc0003ed350)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62

goroutine 30 [runnable]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc0000388c0)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch/mux.go:207 +0x66
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch.NewBroadcaster
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch/mux.go:75 +0xcc

goroutine 31 [chan receive, 2 minutes]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1(0x1abf660, 0xc000384420, 0xc0002328d0)
        /home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/client-go/tools/record/e
```

This happened while running on 1.0-beta6 against an EKS instance (1.10.3, afaict).

Ideally there'd be a better error message and not a crash, but I think even better would be to have an option to automatically issue certificates if there aren't any already available for that ingress domain.

**Comment by cv** [comment]
Upon further investigation, it looks like this is happening when a `certificate-arn` is added and there's no `listen-ports` annotation added.

The trace seems to be pointing at this line: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/d1782a0041b641657aead087e30b9983915fa97d/internal/alb/ls/listener.go#L331

**Comment by cv** [comment]
This is fixed by #610

**Comment by sslotnick-isp** [comment]
FYI I was able to produce a similar panic when the certificate exists but cannot be accessed. I was attempting to access a certificate using a cross-account role:

```
F0914 02:56:14.166465       1 albingresses.go:167] ERROR: Work Unit failed due to a recoverable error: 'runtime error: invalid memory address or nil pointer dereference'
, Stack Trace:
 goroutine 367 [running]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1.1(0xc000b2df18, 0xc000a8bf00)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:60 +0xbc
panic(0x1687b00, 0x2c25d90)
	/home/travis/.gimme/versions/go/src/runtime/panic.go:513 +0x1b9
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls.(*Listener).DefaultActionArn(...)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/ls/listener.go:329
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb.(*LoadBalancer).Reconcile(0xc000b18c60, 0xc000b2de30, 0xc000b50210, 0x10, 0x10)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb/loadbalancer.go:314 +0x405
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.(*ALBIngress).Reconcile(0xc0004d5e00, 0xc0005afea8, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingress.go:281 +0x12e
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.ALBIngresses.Reconcile.func1.1(0x1ad8720, 0xc000fc1740, 0x2, 0x0, 0x1, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingresses.go:154 +0xce
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1(0xc000fc16e0, 0xc000554f00, 0xc000a8bf00)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:89 +0x196
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/gopkg.in/go-playground/pool.v3/limited_pool.go:52 +0x53

goroutine 1 [select]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller.(*ALBController).Start(0xc00044cd10)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/alb.go:193 +0x3ff
main.main()
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/cmd/main.go:117 +0x4fd

goroutine 18 [chan receive]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x2c3c9a0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog.init.0
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 33 [syscall]:
os/signal.signal_recv(0x0)
	/home/travis/.gimme/versions/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 46 [chan receive]:
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc0004c5280)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch/mux.go:207 +0x66
created by github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch.NewBroadcaster
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/watch/mux.go:75 +0xcc

goroutine 47 [chan receive]:
main.handleSigterm(0xc00044cd10, 0x1969ad8)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/cmd/main.go:125 +0xa0
created by main.main
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/cmd/main.go:101 +0x43c

goroutine 44 [IO wait]:
internal/poll.runtime_pollWait(0x7faefb99a000, 0x72, 0xc0002a3870)
	/home/travis/.gimme/versions/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00043cb18, 0x72, 0xffffffffffffff00, 0x1ab9320, 0x2bdd4f0)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00043cb18, 0xc000488000, 0x8000, 0x8000)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc00043cb00, 0xc000488000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc00043cb00, 0xc000488000, 0x8000, 0x8000, 0x408a0b, 0xc00002e000, 0x16ad700)
	/home/travis/.gimme/versions/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000434018, 0xc000488000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/net/net.go:177 +0x68
crypto/tls.(*block).readFromUntil(0xc00042a480, 0x1ab7a00, 0xc000434018, 0x5, 0xc000434018, 0x0)
	/home/travis/.gimme/versions/go/src/crypto/tls/conn.go:492 +0x89
crypto/tls.(*Conn).readRecord(0xc00041c700, 0x196a417, 0xc00041c820, 0x155ca00)
	/home/travis/.gimme/versions/go/src/crypto/tls/conn.go:593 +0xdd
crypto/tls.(*Conn).Read(0xc00041c700, 0xc0003bf000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/crypto/tls/conn.go:1145 +0xf1
bufio.(*Reader).Read(0xc000428900, 0xc0003bc3b8, 0x9, 0x9, 0x8675c0, 0x42df0c, 0xc0002a3c50)
	/home/travis/.gimme/versions/go/src/bufio/bufio.go:216 +0x22f
io.ReadAtLeast(0x1ab60e0, 0xc000428900, 0xc0003bc3b8, 0x9, 0x9, 0x9, 0x196a400, 0xc0002a3cf0, 0xc0002a3ce0)
	/home/travis/.gimme/versions/go/src/io/io.go:310 +0x88
io.ReadFull(0x1ab60e0, 0xc000428900, 0xc0003bc3b8, 0x9, 0x9, 0xc00013a000, 0x16a, 0x4000)
	/home/travis/.gimme/versions/go/src/io/io.go:329 +0x58
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2.readFrameHeader(0xc0003bc3b8, 0x9, 0x9, 0x1ab60e0, 0xc000428900, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc0003bc380, 0xc000acdb30, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2/frame.go:492 +0xa3
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc0002a3fb8, 0x1969290, 0xc000068fb8)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2/transport.go:1616 +0x9e
github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc000458700)
	/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/vendor/golang.org/x/net/http2/transp
I0914 02:56:14.166461       1 event.go:221] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"dev", Name:"XXXX", UID:"4b9c5afa-b7be-11e8-9d3e-062d8c36f7b4", APIVersion:"extensions/v1beta1", ResourceVersion:"9284449", FieldPath:""}): type: 'Warning' reason: 'ERROR' Error creating 443 listener: CertificateNotFound: Certificate 'arn:aws:acm:us-west-2:XXXXXXXX:certificate/XXXXXXXXXX' not found
	status code: 400, request id: be20f33f-b7c9-11e8-8f38-4b4c8df36e0e
```

**Comment by cv** [comment]
@sslotnick-isp is it still happening? #610 fixed it for me, and I can't reproduce the issue anymore.
