### ISSUE TITLE
Nil pointer exception on deletion of ingress/service

### ISSUE THREAD

**Issue by tristanstraub** [kubernetes-sigs/aws-alb-ingress-controller#703]
While deleting ingresses/services, recreating and deleting again the following killed alb-ingress-controller: (running quay.io/coreos/alb-ingress-controller:1.0-beta.7)

```
05:58:49
F1031 05:58:49.398742 1 albingresses.go:172] ERROR: Work Unit failed due to a recoverable error: 'runtime error: invalid memory address or nil pointer dereference'

05:58:49
, Stack Trace:

05:58:49
goroutine 27781 [running]:

05:58:49
gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1.1(0xc0004bdf18, 0xc001b26100)

05:58:49
/home/travis/gopath/pkg/mod/gopkg.in/go-playground/pool.v3@v3.1.1/limited_pool.go:60 +0xbc

05:58:49
panic(0x169d5e0, 0x29f7df0)

05:58:49
/home/travis/.gimme/versions/go/src/runtime/panic.go:513 +0x1b5

05:58:49
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb.(*LoadBalancer).Reconcile(0xc002820420, 0xc002d55600, 0xc0025aef68, 0x0, 0x403af3)

05:58:49
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/alb/lb/loadbalancer.go:248 +0x101

05:58:49
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.(*ALBIngress).Reconcile(0xc002351ea0, 0xc002d55698, 0x0, 0x0)

05:58:49
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingress.go:281 +0x138

05:58:49
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress.ALBIngresses.Reconcile.func1.1(0x1af0a00, 0xc001f00fc0, 0x2, 0x0, 0x43df01, 0xc001c06480)

05:58:49
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/albingress/albingresses.go:159 +0x10a

05:58:49
gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker.func1(0xc001f00f00, 0xc0012162a0, 0xc001b26100)

05:58:49
/home/travis/gopath/pkg/mod/gopkg.in/go-playground/pool.v3@v3.1.1/limited_pool.go:89 +0x190

05:58:49
created by gopkg.in/go-playground/pool%2ev3.(*limitedPool).newWorker

05:58:49
/home/travis/gopath/pkg/mod/gopkg.in/go-playground/pool.v3@v3.1.1/limited_pool.go:52 +0x53

05:58:49
goroutine 1 [select]:

05:58:49
github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller.(*ALBController).Start(0xc000416cc0)

05:58:49
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/internal/ingress/controller/alb.go:200 +0x3ff

05:58:49
main.main()

05:58:49
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-alb-ingress-controller/cmd/main.go:122 +0x60c

05:58:49
goroutine 18 [chan receive, 1 minutes]:

05:58:49
github.com/golang/glog.(*loggingT).flushDaemon(0x2a0ea80)

05:58:49
/home/travis/gopath/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b

05:58:49
created by github.com/golang/glog.init.0

05:58:49
/home/travis/gopath/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x203

05:58:49
goroutine 42 [chan receive, 80 minutes]:

05:58:49
k8s.io/client-go/tools/cache.(*sharedProcessor).run(0xc000189500, 0xc00042cae0)

05:58:49
/home/travis/gopath/pkg/mod/k8s.io/client-go@v8.0.0+incompatible/tools/cache/shared_informer.go:425 +0x46

05:58:49
k8s.io/client-go/tools/cache.(*sharedProcessor).run-fm(0xc00042cae0)

05:58:49
/home/travis/gopath/pkg/mod/k8s.io/client-go@v8.0.0+incompatible/tools/cache/shared_informer.go:220 +0x34

05:58:49
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()

05:58:49
/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:54 +0x2e

05:58:49
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000045420, 0xc0004969c0)

05:58:49
/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:71 +0x4f

05:58:49
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start

05:58:49
/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:69 +0x62

05:58:49
goroutine 20 [syscall, 80 minutes]:

05:58:49
os/signal.signal_recv(0x0)

05:58:49
/home/travis/.gimme/versions/go/src/runtime/sigqueue.go:139 +0x9c

05:58:49
os/signal.loop()

05:58:49
/home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:23 +0x22

05:58:49
created by os/signal.init.0

05:58:49
/home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:29 +0x41

05:58:49
goroutine 65 [chan receive, 1 minutes]:

05:58:49
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x42afc6, 0xc00005c5c8, 0x3)

05:58:49
/home/travis/gopath/pkg/mod/k8s.io/client-go@v8.0.0+incompatible/tools/cache/shared_informer.go:549 +0x54

05:58:49
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0xc000019e18, 0x42aad2, 0xc0000b5660)

05:58:49
/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:203 +0x9c

05:58:49
k8s.io/client-go/tools/cache.(*processorListener).run.func1()

05:58:49
/home/travis/gopath/pkg/mod/k8s.io/client-go@v8.0.0+incompatible/tools/cache/shared_informer.go:548 +0x89

05:58:49
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00005c768)

05:58:49
/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:133 +0x54

05:58:49
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000019f68, 0xdf8475800, 0x0, 0x165d001, 0xc00042d020)

05:58:49
/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:134 +0xbb

05:58:49
k8s.io/apimachinery/pkg/util/wait.Until(0xc00005c768, 0xdf8475800, 0xc00042d020)

05:58:49
/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:88 +0x4d

05:58:49
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000115380)

05:58:49
/home/travis/gopath/pkg/mod/k8s.io/client-go@v8.0.0+incompatible/tools/cache/shared_informer.go:546 +0x8d

05:58:49
k8s.io/client-go/tools/cache.(*processorListener).run-fm()

05:58:49
/home/travis/gopath/pkg/mod/k8s.io/client-go@v8.0.0+incompatible/tools/cache/shared_informer.go:390 +0x2a

05:58:49
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000189560, 0xc000245110)

05:58:49
/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:71 +0x4f

05:58:49
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start

05:58:49
/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:69 +0x62

05:58:49
goroutine 30 [select, 1 minutes]:

05:58:49
k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc0003df400)

05:58:49
/home/travis/gopath/pkg/mod/k8s.io/client-go@v8.0.0+incompatible/util/workqueue/delaying_queue.go:206 +0x348

05:58:49
created by k8s.io/client-go/util/workqueue.newDelayingQueue

05:58:49
/home/travis/gopath/pkg/mod/k8s.io/client-go@v8.0.0+incompatible/util/workqueue/delaying_queue.go:54 +0x1ba

05:58:49
goroutine 31 [chan receive, 80 minutes]:

05:58:49
k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc0003b09c0)

05:58:49
/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/watch/mux.go:207 +0x66

05:58:49
created by k8s.io/apimachinery/pkg/watch.NewBroadcaster

05:58:49
/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/watch/mux.go:75 +0xcc

05:58:49
goroutine 28 [IO wait]:

05:58:49
internal/poll.runtime_pollWait(0x7fd1652b4fe0, 0x72, 0xc0000ab878)

05:58:49
/home/travis/.gimme/versions/go/src/runtime/netpoll.go:173 +0x55

05:58:49
internal/poll.(*pollDesc).wait(0xc0003db798, 0x72, 0xffffffffffffff00, 0x1ad43e0, 0x29af4d8)

05:58:49
/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a

05:58:49
internal/poll.(*pollDesc).waitRead(0xc0003db798, 0xc000520000, 0x8000, 0x8000)

05:58:49
/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d

05:58:49
internal/poll.(*FD).Read(0xc0003db780, 0xc000520000, 0x8000, 0x8000, 0x0, 0x0, 0x0)

05:58:49
/home/travis/.gimme/versions/go/src/internal/poll/fd_unix.go:169 +0x174

05:58:49
net.(*netFD).Read(0xc0003db780, 0xc000520000, 0x8000, 0x8000, 0x4089db, 0xc00002e000, 0x16beca0)

05:58:49
/ho
```

**Comment by M00nF1sh** [comment]
This vpcID dereference bug was fixed in our master branch, we'll release a new version soon.

Closing this 😄
